### ISSUE TITLE
AzCopy wrapper using Service Principals

### ISSUE THREAD

**Issue by marc88** [yashmarathe21/py-azcopy-wrapper#1]
How do we Copy blobs between 2 remote storage accounts using this wrapper and, by using the credentials of a Service Principal?

**Comment by yashmarathe21** [comment]
@marc88 Currently this wrapper doesn't provide support for Service Principal Credentials.

However, as per my knowledge, Shared Access Signatures (SAS) tokens can be used for authentication when transferring data between two Azure Storage accounts which is possible from the wapper. 

You can find an  example in this notebook - [examples.ipynb](https://github.com/yashmarathe21/py-azcopy-wrapper/blob/master/examples.ipynb). (Search for "Copy files from one container to container")

But I am unsure about the specs of your use-case. 

I appreciate your input, and I'll plan to add support for Service Principal Credentials in the next version. If you have any further details or specific requirements for this feature, please feel free to share.
